//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.0.0 (NJsonSchema v11.5.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios from 'axios';
import type {
  AxiosError,
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse,
  CancelToken,
} from 'axios';
export default class AuthorizedApiBase {
  protected transformOptions = (options: AxiosRequestConfig): Promise<AxiosRequestConfig> => {
    const newOptions: AxiosRequestConfig = options;

    // needed to prevent double json parsing (axios vs nswag)
    newOptions.transformResponse = undefined;

    newOptions.withCredentials = true;

    return Promise.resolve(newOptions);
  };
}

export interface IAuthApiClient {
    /**
     * @return OK
     */
    login(body: LoginBindingModel,  cancelToken?: CancelToken): Promise<LoginResponseBindingModel>;
}

export class AuthApiClient extends AuthorizedApiBase implements IAuthApiClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "https://localhost:7108";

    }

    /**
     * @return OK
     */
    login(body: LoginBindingModel, cancelToken?: CancelToken): Promise<LoginResponseBindingModel> {
        let url_ = this.baseUrl + "/api/auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: AxiosResponse): Promise<LoginResponseBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = LoginResponseBindingModel.fromJS(resultData200);
            return Promise.resolve<LoginResponseBindingModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<LoginResponseBindingModel>(null as any);
    }
}

export interface IInfoApiClient {
    /**
     * @return OK
     */
    getInfo( cancelToken?: CancelToken): Promise<ApiInfoBindingModel>;
}

export class InfoApiClient extends AuthorizedApiBase implements IInfoApiClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "https://localhost:7108";

    }

    /**
     * @return OK
     */
    getInfo( cancelToken?: CancelToken): Promise<ApiInfoBindingModel> {
        let url_ = this.baseUrl + "/api/info";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetInfo(_response);
        });
    }

    protected processGetInfo(response: AxiosResponse): Promise<ApiInfoBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = ApiInfoBindingModel.fromJS(resultData200);
            return Promise.resolve<ApiInfoBindingModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiInfoBindingModel>(null as any);
    }
}

export interface IRolesApiClient {
    /**
     * @return OK
     */
    createRole(body: CreateRoleBindingModel,  cancelToken?: CancelToken): Promise<BasicRoleBindingModel>;
    /**
     * @return No Content
     */
    deleteRole(body: DeleteRoleBindingModel,  cancelToken?: CancelToken): Promise<void>;
    /**
     * @return OK
     */
    getAllRoles( cancelToken?: CancelToken): Promise<BasicRoleBindingModel[]>;
    /**
     * @return OK
     */
    updateRole(body: UpdateRoleBindingModel,  cancelToken?: CancelToken): Promise<BasicRoleBindingModel>;
}

export class RolesApiClient extends AuthorizedApiBase implements IRolesApiClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "https://localhost:7108";

    }

    /**
     * @return OK
     */
    createRole(body: CreateRoleBindingModel, cancelToken?: CancelToken): Promise<BasicRoleBindingModel> {
        let url_ = this.baseUrl + "/api/roles";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreateRole(_response);
        });
    }

    protected processCreateRole(response: AxiosResponse): Promise<BasicRoleBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BasicRoleBindingModel.fromJS(resultData200);
            return Promise.resolve<BasicRoleBindingModel>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BasicRoleBindingModel>(null as any);
    }

    /**
     * @return No Content
     */
    deleteRole(body: DeleteRoleBindingModel, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/roles";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "DELETE",
            url: url_,
            headers: {
                "Content-Type": "*/*",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDeleteRole(_response);
        });
    }

    protected processDeleteRole(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getAllRoles( cancelToken?: CancelToken): Promise<BasicRoleBindingModel[]> {
        let url_ = this.baseUrl + "/api/roles";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetAllRoles(_response);
        });
    }

    protected processGetAllRoles(response: AxiosResponse): Promise<BasicRoleBindingModel[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(BasicRoleBindingModel.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return Promise.resolve<BasicRoleBindingModel[]>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BasicRoleBindingModel[]>(null as any);
    }

    /**
     * @return OK
     */
    updateRole(body: UpdateRoleBindingModel, cancelToken?: CancelToken): Promise<BasicRoleBindingModel> {
        let url_ = this.baseUrl + "/api/roles";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUpdateRole(_response);
        });
    }

    protected processUpdateRole(response: AxiosResponse): Promise<BasicRoleBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BasicRoleBindingModel.fromJS(resultData200);
            return Promise.resolve<BasicRoleBindingModel>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BasicRoleBindingModel>(null as any);
    }
}

export interface ISkillsApiClient {
    /**
     * @return OK
     */
    createSkill(body: CreateSkillBindingModel,  cancelToken?: CancelToken): Promise<BasicSkillBindingModel>;
    /**
     * @return OK
     */
    get_All_Skills( cancelToken?: CancelToken): Promise<BasicSkillBindingModel[]>;
    /**
     * @return OK
     */
    updateSkill(body: UpdateSkillBindingModel,  cancelToken?: CancelToken): Promise<BasicSkillBindingModel>;
    /**
     * @return No Content
     */
    deleteSkill( cancelToken?: CancelToken): Promise<void>;
    /**
     * @return OK
     */
    get_Skill_By_Id( cancelToken?: CancelToken): Promise<SkillDetailBindingModel>;
    /**
     * @return OK
     */
    updateSkillReviewers(body: UpdateSkillReviewersBindingModel,  cancelToken?: CancelToken): Promise<SkillDetailBindingModel>;
}

export class SkillsApiClient extends AuthorizedApiBase implements ISkillsApiClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "https://localhost:7108";

    }

    /**
     * @return OK
     */
    createSkill(body: CreateSkillBindingModel, cancelToken?: CancelToken): Promise<BasicSkillBindingModel> {
        let url_ = this.baseUrl + "/api/skills";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreateSkill(_response);
        });
    }

    protected processCreateSkill(response: AxiosResponse): Promise<BasicSkillBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BasicSkillBindingModel.fromJS(resultData200);
            return Promise.resolve<BasicSkillBindingModel>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BasicSkillBindingModel>(null as any);
    }

    /**
     * @return OK
     */
    get_All_Skills( cancelToken?: CancelToken): Promise<BasicSkillBindingModel[]> {
        let url_ = this.baseUrl + "/api/skills";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_All_Skills(_response);
        });
    }

    protected processGet_All_Skills(response: AxiosResponse): Promise<BasicSkillBindingModel[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(BasicSkillBindingModel.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return Promise.resolve<BasicSkillBindingModel[]>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BasicSkillBindingModel[]>(null as any);
    }

    /**
     * @return OK
     */
    updateSkill(body: UpdateSkillBindingModel, cancelToken?: CancelToken): Promise<BasicSkillBindingModel> {
        let url_ = this.baseUrl + "/api/skills";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUpdateSkill(_response);
        });
    }

    protected processUpdateSkill(response: AxiosResponse): Promise<BasicSkillBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BasicSkillBindingModel.fromJS(resultData200);
            return Promise.resolve<BasicSkillBindingModel>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BasicSkillBindingModel>(null as any);
    }

    /**
     * @return No Content
     */
    deleteSkill( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/skills/{id}";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDeleteSkill(_response);
        });
    }

    protected processDeleteSkill(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    get_Skill_By_Id( cancelToken?: CancelToken): Promise<SkillDetailBindingModel> {
        let url_ = this.baseUrl + "/api/skills/{id}";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet_Skill_By_Id(_response);
        });
    }

    protected processGet_Skill_By_Id(response: AxiosResponse): Promise<SkillDetailBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = SkillDetailBindingModel.fromJS(resultData200);
            return Promise.resolve<SkillDetailBindingModel>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<SkillDetailBindingModel>(null as any);
    }

    /**
     * @return OK
     */
    updateSkillReviewers(body: UpdateSkillReviewersBindingModel, cancelToken?: CancelToken): Promise<SkillDetailBindingModel> {
        let url_ = this.baseUrl + "/api/skills/{id}/reviewers";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUpdateSkillReviewers(_response);
        });
    }

    protected processUpdateSkillReviewers(response: AxiosResponse): Promise<SkillDetailBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = SkillDetailBindingModel.fromJS(resultData200);
            return Promise.resolve<SkillDetailBindingModel>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<SkillDetailBindingModel>(null as any);
    }
}

export interface IUsersApiClient {
    /**
     * @return No Content
     */
    changeOwnPassword(body: ChangeOwnPasswordBindingModel,  cancelToken?: CancelToken): Promise<void>;
    /**
     * @return OK
     */
    createUser(body: CreateUserBindingModel,  cancelToken?: CancelToken): Promise<BasicUserBindingModel>;
    /**
     * @return No Content
     */
    deleteUser(body: DeleteUserBindingModel,  cancelToken?: CancelToken): Promise<void>;
    /**
     * @return OK
     */
    getUsers( cancelToken?: CancelToken): Promise<BasicUserBindingModel[]>;
    /**
     * @return OK
     */
    update_User(body: UpdateUserBindingModel,  cancelToken?: CancelToken): Promise<BasicUserBindingModel>;
}

export class UsersApiClient extends AuthorizedApiBase implements IUsersApiClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "https://localhost:7108";

    }

    /**
     * @return No Content
     */
    changeOwnPassword(body: ChangeOwnPasswordBindingModel, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/users/change-password";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processChangeOwnPassword(_response);
        });
    }

    protected processChangeOwnPassword(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    createUser(body: CreateUserBindingModel, cancelToken?: CancelToken): Promise<BasicUserBindingModel> {
        let url_ = this.baseUrl + "/api/users";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreateUser(_response);
        });
    }

    protected processCreateUser(response: AxiosResponse): Promise<BasicUserBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BasicUserBindingModel.fromJS(resultData200);
            return Promise.resolve<BasicUserBindingModel>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BasicUserBindingModel>(null as any);
    }

    /**
     * @return No Content
     */
    deleteUser(body: DeleteUserBindingModel, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/users";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "DELETE",
            url: url_,
            headers: {
                "Content-Type": "*/*",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDeleteUser(_response);
        });
    }

    protected processDeleteUser(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getUsers( cancelToken?: CancelToken): Promise<BasicUserBindingModel[]> {
        let url_ = this.baseUrl + "/api/users";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetUsers(_response);
        });
    }

    protected processGetUsers(response: AxiosResponse): Promise<BasicUserBindingModel[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(BasicUserBindingModel.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return Promise.resolve<BasicUserBindingModel[]>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BasicUserBindingModel[]>(null as any);
    }

    /**
     * @return OK
     */
    update_User(body: UpdateUserBindingModel, cancelToken?: CancelToken): Promise<BasicUserBindingModel> {
        let url_ = this.baseUrl + "/api/users";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUpdate_User(_response);
        });
    }

    protected processUpdate_User(response: AxiosResponse): Promise<BasicUserBindingModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BasicUserBindingModel.fromJS(resultData200);
            return Promise.resolve<BasicUserBindingModel>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BasicUserBindingModel>(null as any);
    }
}

export class ApiInfoBindingModel implements IApiInfoBindingModel {
    version!: string | undefined;
    systemEnvironment!: string | undefined;

    constructor(data?: IApiInfoBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.version = _data["version"];
            this.systemEnvironment = _data["systemEnvironment"];
        }
    }

    static fromJS(data: any): ApiInfoBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new ApiInfoBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["version"] = this.version;
        data["systemEnvironment"] = this.systemEnvironment;
        return data;
    }
}

export interface IApiInfoBindingModel {
    version: string | undefined;
    systemEnvironment: string | undefined;
}

export class BasicRoleBindingModel implements IBasicRoleBindingModel {
    id!: string;
    name!: string | undefined;

    constructor(data?: IBasicRoleBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): BasicRoleBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new BasicRoleBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface IBasicRoleBindingModel {
    id: string;
    name: string | undefined;
}

export class BasicSkillBindingModel implements IBasicSkillBindingModel {
    id!: string;
    name!: string | undefined;

    constructor(data?: IBasicSkillBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): BasicSkillBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new BasicSkillBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface IBasicSkillBindingModel {
    id: string;
    name: string | undefined;
}

export class BasicUserBindingModel implements IBasicUserBindingModel {
    id!: string;
    userName!: string | undefined;
    displayName!: string | undefined;

    constructor(data?: IBasicUserBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.userName = _data["userName"];
            this.displayName = _data["displayName"];
        }
    }

    static fromJS(data: any): BasicUserBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new BasicUserBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["userName"] = this.userName;
        data["displayName"] = this.displayName;
        return data;
    }
}

export interface IBasicUserBindingModel {
    id: string;
    userName: string | undefined;
    displayName: string | undefined;
}

export class ChangeOwnPasswordBindingModel implements IChangeOwnPasswordBindingModel {
    currentPassword!: string | undefined;
    newPassword!: string | undefined;

    constructor(data?: IChangeOwnPasswordBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.currentPassword = _data["currentPassword"];
            this.newPassword = _data["newPassword"];
        }
    }

    static fromJS(data: any): ChangeOwnPasswordBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new ChangeOwnPasswordBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["currentPassword"] = this.currentPassword;
        data["newPassword"] = this.newPassword;
        return data;
    }
}

export interface IChangeOwnPasswordBindingModel {
    currentPassword: string | undefined;
    newPassword: string | undefined;
}

export class CreateRoleBindingModel implements ICreateRoleBindingModel {
    name!: string;

    constructor(data?: ICreateRoleBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): CreateRoleBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new CreateRoleBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        return data;
    }
}

export interface ICreateRoleBindingModel {
    name: string;
}

export class CreateSkillBindingModel implements ICreateSkillBindingModel {
    name!: string;
    description!: string | undefined;

    constructor(data?: ICreateSkillBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): CreateSkillBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSkillBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        return data;
    }
}

export interface ICreateSkillBindingModel {
    name: string;
    description: string | undefined;
}

export class CreateUserBindingModel implements ICreateUserBindingModel {
    userName!: string | undefined;
    displayName!: string | undefined;
    password!: string | undefined;

    constructor(data?: ICreateUserBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userName = _data["userName"];
            this.displayName = _data["displayName"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): CreateUserBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new CreateUserBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userName"] = this.userName;
        data["displayName"] = this.displayName;
        data["password"] = this.password;
        return data;
    }
}

export interface ICreateUserBindingModel {
    userName: string | undefined;
    displayName: string | undefined;
    password: string | undefined;
}

export class DeleteRoleBindingModel implements IDeleteRoleBindingModel {
    id!: string;

    constructor(data?: IDeleteRoleBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): DeleteRoleBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new DeleteRoleBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data;
    }
}

export interface IDeleteRoleBindingModel {
    id: string;
}

export class DeleteUserBindingModel implements IDeleteUserBindingModel {
    id!: string;

    constructor(data?: IDeleteUserBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): DeleteUserBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new DeleteUserBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data;
    }
}

export interface IDeleteUserBindingModel {
    id: string;
}

export class LoginBindingModel implements ILoginBindingModel {
    userName!: string | undefined;
    password!: string | undefined;
    rememberMe!: boolean;

    constructor(data?: ILoginBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userName = _data["userName"];
            this.password = _data["password"];
            this.rememberMe = _data["rememberMe"];
        }
    }

    static fromJS(data: any): LoginBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new LoginBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userName"] = this.userName;
        data["password"] = this.password;
        data["rememberMe"] = this.rememberMe;
        return data;
    }
}

export interface ILoginBindingModel {
    userName: string | undefined;
    password: string | undefined;
    rememberMe: boolean;
}

export class LoginResponseBindingModel implements ILoginResponseBindingModel {
    token!: string | undefined;

    constructor(data?: ILoginResponseBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.token = _data["token"];
        }
    }

    static fromJS(data: any): LoginResponseBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new LoginResponseBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["token"] = this.token;
        return data;
    }
}

export interface ILoginResponseBindingModel {
    token: string | undefined;
}

export class SkillDetailBindingModel implements ISkillDetailBindingModel {
    id!: string;
    name!: string | undefined;
    description!: string | undefined;
    possibleReviewers!: BasicUserBindingModel[] | undefined;

    constructor(data?: ISkillDetailBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            if (Array.isArray(_data["possibleReviewers"])) {
                this.possibleReviewers = [] as any;
                for (let item of _data["possibleReviewers"])
                    this.possibleReviewers!.push(BasicUserBindingModel.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SkillDetailBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new SkillDetailBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        if (Array.isArray(this.possibleReviewers)) {
            data["possibleReviewers"] = [];
            for (let item of this.possibleReviewers)
                data["possibleReviewers"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ISkillDetailBindingModel {
    id: string;
    name: string | undefined;
    description: string | undefined;
    possibleReviewers: BasicUserBindingModel[] | undefined;
}

export class UpdateRoleBindingModel implements IUpdateRoleBindingModel {
    id!: string;
    name!: string;

    constructor(data?: IUpdateRoleBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): UpdateRoleBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateRoleBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface IUpdateRoleBindingModel {
    id: string;
    name: string;
}

export class UpdateSkillBindingModel implements IUpdateSkillBindingModel {
    id!: string;
    name!: string;
    description!: string | undefined;

    constructor(data?: IUpdateSkillBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): UpdateSkillBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateSkillBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        return data;
    }
}

export interface IUpdateSkillBindingModel {
    id: string;
    name: string;
    description: string | undefined;
}

export class UpdateSkillReviewersBindingModel implements IUpdateSkillReviewersBindingModel {
    skillId!: string;
    reviewerUserIds!: string[];

    constructor(data?: IUpdateSkillReviewersBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.reviewerUserIds = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.skillId = _data["skillId"];
            if (Array.isArray(_data["reviewerUserIds"])) {
                this.reviewerUserIds = [] as any;
                for (let item of _data["reviewerUserIds"])
                    this.reviewerUserIds!.push(item);
            }
        }
    }

    static fromJS(data: any): UpdateSkillReviewersBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateSkillReviewersBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["skillId"] = this.skillId;
        if (Array.isArray(this.reviewerUserIds)) {
            data["reviewerUserIds"] = [];
            for (let item of this.reviewerUserIds)
                data["reviewerUserIds"].push(item);
        }
        return data;
    }
}

export interface IUpdateSkillReviewersBindingModel {
    skillId: string;
    reviewerUserIds: string[];
}

export class UpdateUserBindingModel implements IUpdateUserBindingModel {
    id!: string;
    userName!: string | undefined;
    displayName!: string | undefined;
    password!: string | undefined;

    constructor(data?: IUpdateUserBindingModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.userName = _data["userName"];
            this.displayName = _data["displayName"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): UpdateUserBindingModel {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateUserBindingModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["userName"] = this.userName;
        data["displayName"] = this.displayName;
        data["password"] = this.password;
        return data;
    }
}

export interface IUpdateUserBindingModel {
    id: string;
    userName: string | undefined;
    displayName: string | undefined;
    password: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}

/* eslint-disable class-methods-use-this */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable unicorn/no-abusive-eslint-disable */
// imported (but unsued) because they are qeuired by the nswag generator