// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ITTitans.Hackathon2025.EntityModel.Migrations
{
    /// <inheritdoc />
    public partial class AddReviewCommentToSupplyCertificateWorkflow : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ReviewComment",
                table: "SupplyCertificateWorkflow",
                type: "character varying(2500)",
                maxLength: 2500,
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ReviewComment",
                table: "SupplyCertificateWorkflow");
        }
    }
}
