// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ITTitans.Hackathon2025.EntityModel.Migrations
{
    /// <inheritdoc />
    public partial class UpdateSkillEntityModel : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SkillAssignment_Skill_SkillId",
                table: "SkillAssignment");

            migrationBuilder.DropForeignKey(
                name: "FK_SkillAssignment_SupplyCertificateWorkflow_WorkflowId",
                table: "SkillAssignment");

            migrationBuilder.AddColumn<string>(
                name: "ReviewComment",
                table: "SupplyCertificateWorkflow",
                type: "character varying(2500)",
                maxLength: 2500,
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SkillId",
                table: "SupplyCertificateWorkflow",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AlterColumn<Guid>(
                name: "WorkflowId",
                table: "SkillAssignment",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "SkillId",
                table: "SkillAssignment",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_SupplyCertificateWorkflow_SkillId",
                table: "SupplyCertificateWorkflow",
                column: "SkillId");

            migrationBuilder.AddForeignKey(
                name: "FK_SkillAssignment_Skill_SkillId",
                table: "SkillAssignment",
                column: "SkillId",
                principalTable: "Skill",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_SkillAssignment_SupplyCertificateWorkflow_WorkflowId",
                table: "SkillAssignment",
                column: "WorkflowId",
                principalTable: "SupplyCertificateWorkflow",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_SupplyCertificateWorkflow_Skill_SkillId",
                table: "SupplyCertificateWorkflow",
                column: "SkillId",
                principalTable: "Skill",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SkillAssignment_Skill_SkillId",
                table: "SkillAssignment");

            migrationBuilder.DropForeignKey(
                name: "FK_SkillAssignment_SupplyCertificateWorkflow_WorkflowId",
                table: "SkillAssignment");

            migrationBuilder.DropForeignKey(
                name: "FK_SupplyCertificateWorkflow_Skill_SkillId",
                table: "SupplyCertificateWorkflow");

            migrationBuilder.DropIndex(
                name: "IX_SupplyCertificateWorkflow_SkillId",
                table: "SupplyCertificateWorkflow");

            migrationBuilder.DropColumn(
                name: "ReviewComment",
                table: "SupplyCertificateWorkflow");

            migrationBuilder.DropColumn(
                name: "SkillId",
                table: "SupplyCertificateWorkflow");

            migrationBuilder.AlterColumn<Guid>(
                name: "WorkflowId",
                table: "SkillAssignment",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AlterColumn<Guid>(
                name: "SkillId",
                table: "SkillAssignment",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AddForeignKey(
                name: "FK_SkillAssignment_Skill_SkillId",
                table: "SkillAssignment",
                column: "SkillId",
                principalTable: "Skill",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_SkillAssignment_SupplyCertificateWorkflow_WorkflowId",
                table: "SkillAssignment",
                column: "WorkflowId",
                principalTable: "SupplyCertificateWorkflow",
                principalColumn: "Id");
        }
    }
}
